In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from string import punctuation
from nltk.tokenize import word_tokenize,sent_tokenize
from wordcloud import WordCloud
import seaborn as sn
import re

In [2]:
pd.set_option("max_colwidth",None)

In [3]:
df1=pd.read_csv("tweet.csv")

In [4]:
df1.head()

tweets  \
0                          Be aware  dirty step to get money  #staylight #staywhite  #sarcastic #moralneeded @… https://t.co/Oj6BdyX3WG   
1                                                      #sarcasm for #people who don't understand #diy #artattack http://t.co/rtyYmuDVUS   
2  @IminworkJeremy @medsingle #DailyMail readers being sensible as always #shocker #sarcastic #dailyfail #inHuntspocket #theyhatethenhs   
3                                                                               @wilw Why do I get the feeling you like games? #sarcasm   
4                                                           -@TeacherArthurG @rweingarten You probably just missed the text. #sarcastic   

        class  
0  figurative  
1  figurative  
2  figurative  
3  figurative  
4  figurative

In [5]:
df=df1.copy()

In [6]:
#convrt into lower case
df["tweets"]=df["tweets"].str.lower()

In [7]:
#remove html tags
def remove_html(text):
    pattern=re.compile("<.*?>")
    return pattern.sub(r'',text)

In [8]:
df["tweets"]=df["tweets"].apply(remove_html)

In [9]:
#remove urls
def remove_urls(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [10]:
df["tweets"]=df["tweets"].apply(remove_urls)

In [11]:
#remove puncutations
df["tweets"]=df["tweets"].str.replace("[^\w\s]",'')

C:\Users\Dell\AppData\Local\Temp\ipykernel_8936\3914944895.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df["tweets"]=df["tweets"].str.replace("[^\w\s]",'')


In [12]:
#remove stopwords
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
stopword=stopwords.words("english")
df["tweets"]=df["tweets"].apply(lambda x:" ".join(x for x in x.split() if x not in stopword))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
#remove emojis
import emoji

def deEmojis(text):
    regrex_pattern = re.compile(pattern = "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags = re.UNICODE)
    return regrex_pattern.sub(r'',text)


In [14]:
df["tweets"]=df["tweets"].apply(deEmojis)

In [15]:
#remove numerical values
df["tweets"]=df["tweets"].str.replace("\d+",'')

C:\Users\Dell\AppData\Local\Temp\ipykernel_8936\1695435949.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df["tweets"]=df["tweets"].str.replace("\d+",'')


In [16]:
df["token_tweets"]=df["tweets"].apply(word_tokenize)

In [17]:
df.head()

tweets  \
0                                                 aware dirty step get money staylight staywhite sarcastic moralneeded   
1                                                                         sarcasm people dont understand diy artattack   
2  iminworkjeremy medsingle dailymail readers sensible always shocker sarcastic dailyfail inhuntspocket theyhatethenhs   
3                                                                                  wilw get feeling like games sarcasm   
4                                                            teacherarthurg rweingarten probably missed text sarcastic   

        class  \
0  figurative   
1  figurative   
2  figurative   
3  figurative   
4  figurative   

                                                                                                                      token_tweets  
0                                                   [aware, dirty, step, get, money, staylight, staywhite, sarcastic, moralneeded]  
1                                                                              [sarcasm, people, dont, understand, diy, artattack]  
2  [iminworkjeremy, medsingle, dailymail, readers, sensible, always, shocker, sarcastic, dailyfail, inhuntspocket, theyhatethenhs]  
3                                                                                       [wilw, get, feeling, like, games, sarcasm]  
4                                                                 [teacherarthurg, rweingarten, probably, missed, text, sarcastic]

In [18]:
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()

def lemmatize_text(text):
    return [lemmatizer.lemmatize(w) for w in w_tokenizer.tokenize(text)]

In [19]:
df["tweets"]=df["tweets"].apply(lemmatize_text)

In [20]:
df.head()

tweets  \
0                                                  [aware, dirty, step, get, money, staylight, staywhite, sarcastic, moralneeded]   
1                                                                             [sarcasm, people, dont, understand, diy, artattack]   
2  [iminworkjeremy, medsingle, dailymail, reader, sensible, always, shocker, sarcastic, dailyfail, inhuntspocket, theyhatethenhs]   
3                                                                                       [wilw, get, feeling, like, game, sarcasm]   
4                                                                [teacherarthurg, rweingarten, probably, missed, text, sarcastic]   

        class  \
0  figurative   
1  figurative   
2  figurative   
3  figurative   
4  figurative   

                                                                                                                      token_tweets  
0                                                   [aware, dirty, step, get, money, staylight, staywhite, sarcastic, moralneeded]  
1                                                                              [sarcasm, people, dont, understand, diy, artattack]  
2  [iminworkjeremy, medsingle, dailymail, readers, sensible, always, shocker, sarcastic, dailyfail, inhuntspocket, theyhatethenhs]  
3                                                                                       [wilw, get, feeling, like, games, sarcasm]  
4                                                                 [teacherarthurg, rweingarten, probably, missed, text, sarcastic]

In [21]:
def form_sentence(mylist):
    return ' '.join(mylist)
df['clean_tweets']=df['token_tweets'].apply(form_sentence)
df.head()

tweets  \
0                                                  [aware, dirty, step, get, money, staylight, staywhite, sarcastic, moralneeded]   
1                                                                             [sarcasm, people, dont, understand, diy, artattack]   
2  [iminworkjeremy, medsingle, dailymail, reader, sensible, always, shocker, sarcastic, dailyfail, inhuntspocket, theyhatethenhs]   
3                                                                                       [wilw, get, feeling, like, game, sarcasm]   
4                                                                [teacherarthurg, rweingarten, probably, missed, text, sarcastic]   

        class  \
0  figurative   
1  figurative   
2  figurative   
3  figurative   
4  figurative   

                                                                                                                      token_tweets  \
0                                                   [aware, dirty, step, get, money, staylight, staywhite, sarcastic, moralneeded]   
1                                                                              [sarcasm, people, dont, understand, diy, artattack]   
2  [iminworkjeremy, medsingle, dailymail, readers, sensible, always, shocker, sarcastic, dailyfail, inhuntspocket, theyhatethenhs]   
3                                                                                       [wilw, get, feeling, like, games, sarcasm]   
4                                                                 [teacherarthurg, rweingarten, probably, missed, text, sarcastic]   

                                                                                                          clean_tweets  
0                                                 aware dirty step get money staylight staywhite sarcastic moralneeded  
1                                                                         sarcasm people dont understand diy artattack  
2  iminworkjeremy medsingle dailymail readers sensible always shocker sarcastic dailyfail inhuntspocket theyhatethenhs  
3                                                                                  wilw get feeling like games sarcasm  
4                                                            teacherarthurg rweingarten probably missed text sarcastic

In [22]:
df['class'] = df['class'].replace({"figurative":0,"irony":1,"regular":2,"sarcasm":3})

In [23]:
X=df['clean_tweets']
y=df['class']

In [24]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
print(X_train.shape,X_test.shape)

(65126,) (16282,)


# TFIDF

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer  
vectorizer1 = TfidfVectorizer(max_features=200, ngram_range=(1,1))  
tfidf_train1=vectorizer1.fit_transform(X_train).toarray()
print(vectorizer1.vocabulary_)

{'oh': 114, 'look': 87, 'fun': 40, 'ironic': 70, 'love': 89, 'irony': 71, 'like': 82, 'sarcasm': 132, 'guy': 57, 'bad': 8, 'im': 67, 'today': 166, 'little': 83, 'us': 174, 'sure': 148, 'dont': 27, 'need': 106, 'thank': 156, 'would': 191, 'talk': 150, 'back': 7, 'via': 176, 'nice': 111, 'right': 129, 'going': 50, 'education': 29, 'thing': 161, 'free': 38, 'social': 142, 'game': 42, 'keep': 75, 'two': 173, 'making': 93, 'drugs': 28, 'politics': 123, 'news': 109, 'next': 110, 'cant': 16, 'make': 91, 'get': 43, 'tweet': 171, 'tech': 153, 'new': 108, 'video': 177, 'think': 163, 'know': 77, 'mean': 97, 'say': 135, 'isnt': 72, 'real': 127, 'funny': 41, 'didnt': 24, 'makes': 92, 'lol': 85, 'getting': 45, 'yet': 198, 'still': 146, 'doesnt': 25, 'big': 12, 'called': 15, 'people': 118, 'hate': 61, 'everyone': 33, 'tell': 154, 'school': 137, 'take': 149, 'day': 21, 'got': 54, 'years': 196, 'yes': 197, 'black': 13, 'thanks': 157, 'really': 128, 'top': 168, 'job': 74, 'thats': 158, 'one': 116, 'time

In [27]:
vectorizer2 = TfidfVectorizer(max_features=200, ngram_range=(2,2)) 
tfidf_train2=vectorizer2.fit_transform(X_train).toarray()
print(vectorizer2.vocabulary_)

{'love irony': 116, 'today sarcasm': 179, 'dont need': 37, 'would like': 192, 'back sarcasm': 4, 'right sarcasm': 154, 'love sarcasm': 119, 'game sarcasm': 59, 'hillary clinton': 77, 'didnt know': 29, 'makes sense': 120, 'lol sarcasm': 112, 'say sarcasm': 161, 'can not': 11, 'dont know': 34, 'gon na': 62, 'tonight sarcasm': 180, 'much better': 125, 'late night': 102, 'funny sarcasm': 56, 'dont think': 38, 'one irony': 137, 'fun sarcasm': 52, 'great sarcasm': 71, 'news politics': 130, 'politics intelmm': 150, 'intelmm osint': 88, 'donald trump': 31, 'cant wait': 15, 'humor funny': 80, 'last night': 100, 'ever sarcasm': 45, 'us sarcasm': 183, 'dont love': 36, 'sounds like': 167, 'oh irony': 135, 'new york': 129, 'meme humor': 122, 'funny pictures': 55, 'pictures pict': 146, 'pict funnypictures': 145, 'funnypictures funnytweets': 57, 'funnytweets humor': 58, 'gop debate': 67, 'first time': 51, 'politics health': 149, 'health entertainment': 75, 'funny humor': 54, 'didnt see': 30, 'coming 

In [28]:
vectorizer3 = TfidfVectorizer(max_features=200, ngram_range=(3,3)) 
tfidf_train3=vectorizer3.fit_transform(X_train).toarray()
print(vectorizer3.vocabulary_)

{'huge network politics': 91, 'washingtonpost news hnn': 188, 'vascable politics magazine': 186, 'meeting man dreams': 120, 'man dreams meeting': 119, 'dreams meeting beautiful': 31, 'ironic dont think': 105, 'news politics intelmm': 133, 'politics intelmm osint': 153, 'drugs druggists sundries': 33, 'druggists sundries wholesale': 32, 'via rfunny funny': 187, 'rfunny funny lol': 158, 'funny lol haha': 57, 'lol haha humor': 114, 'haha humor lmao': 84, 'humor lmao lmfao': 94, 'diet food yummy': 29, 'food yummy drugs': 48, 'yummy drugs pain': 199, 'drugs pain natural': 34, 'gop ccot gopdebate': 72, 'lol meme humor': 115, 'funny pictures pict': 59, 'pictures pict funnypictures': 150, 'pict funnypictures funnytweets': 148, 'funnypictures funnytweets humor': 62, 'im pretty sure': 99, 'news politics health': 132, 'politics health entertainment': 152, 'didnt see coming': 28, 'see coming sarcasm': 163, 'android design android': 0, 'design android education': 23, 'android education design': 1, 

In [29]:
from scipy.sparse import hstack
# Fit and transform the vectorizers on the training data
tfidf_train1 = vectorizer1.fit_transform(X_train)
tfidf_train2 = vectorizer2.fit_transform(X_train)
tfidf_train3 = vectorizer3.fit_transform(X_train)

# Transform the test data using the fitted vectorizers
tfidf_test1 = vectorizer1.transform(X_test)
tfidf_test2 = vectorizer2.transform(X_test)
tfidf_test3 = vectorizer3.transform(X_test)

In [30]:
# Combine the TF-IDF vectors
combined_train = hstack([tfidf_train1, tfidf_train2, tfidf_train3]).toarray()
combined_test = hstack([tfidf_test1, tfidf_test2, tfidf_test3]).toarray()

# Create a logistic regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='newton-cg',random_state=42,C=0.5,n_jobs=-1)

# Fit the model on the combined TF-IDF vectors
model.fit(combined_train, y_train)

# Make predictions on the test data
y_pred = model.predict(combined_test)

# Evaluate the model on the test data
accuracy = model.score(combined_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.7407566638005159


In [31]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Classification Report: \n", classification_report(y_test, y_pred))

print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
cf_matrix=classification_report(y_test, y_pred)

Classification Report: 
               precision    recall  f1-score   support

           0       0.27      0.00      0.01      4179
           1       0.67      0.99      0.80      4276
           2       0.99      1.00      1.00      3696
           3       0.66      0.99      0.80      4131

    accuracy                           0.74     16282
   macro avg       0.65      0.75      0.65     16282
weighted avg       0.64      0.74      0.64     16282

Confusion Matrix: 
 [[  15 2075    7 2082]
 [  19 4248    9    0]
 [   0    1 3695    0]
 [  21    0    7 4103]]


In [32]:
from sklearn.naive_bayes import MultinomialNB

# Create a Naive Bayes model
model = MultinomialNB()

# Fit the model on the combined TF-IDF vectors
model.fit(combined_train, y_train)

# Make predictions on the test data
y_pred1 = model.predict(combined_test)

# Evaluate the model on the test data
accuracy = model.score(combined_test, y_test)
print("Accuracy:", accuracy)

# Generate classification report
print("Classification Report:")
print(classification_report(y_test, y_pred1))

# Generate confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred1))

Accuracy: 0.6855423166687139
Classification Report:
              precision    recall  f1-score   support

           0       0.32      0.15      0.21      4179
           1       0.66      0.85      0.74      4276
           2       0.98      0.94      0.96      3696
           3       0.65      0.83      0.73      4131

    accuracy                           0.69     16282
   macro avg       0.65      0.69      0.66     16282
weighted avg       0.64      0.69      0.65     16282

Confusion Matrix:
[[ 642 1793   18 1726]
 [ 620 3632   23    1]
 [  52   87 3479   78]
 [ 706    1   15 3409]]


In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


rf_model = RandomForestClassifier(n_estimators=200,min_samples_split=10,
                                  criterion='gini',
                                  bootstrap=True, 
                                  random_state=42,
                                  n_jobs=-1)
rf_model.fit(combined_train, y_train)

y_pred2 = rf_model.predict(combined_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred2)
print("Accuracy:", accuracy)

confusion_mat = confusion_matrix(y_test, y_pred2)
print("Confusion Matrix: \n", confusion_mat)

classification_report = classification_report(y_test, y_pred2)
print("classification_report: \n",classification_report)

Accuracy: 0.6549563935634443
Confusion Matrix: 
 [[ 131 2030    3 2015]
 [ 853 3420    3    0]
 [   0    3 3693    0]
 [ 705    3    3 3420]]
classification_report: 
               precision    recall  f1-score   support

           0       0.08      0.03      0.04      4179
           1       0.63      0.80      0.70      4276
           2       1.00      1.00      1.00      3696
           3       0.63      0.83      0.72      4131

    accuracy                           0.65     16282
   macro avg       0.58      0.66      0.62     16282
weighted avg       0.57      0.65      0.60     16282



In [34]:
import gensim
from gensim.utils import simple_preprocess
tweets=df['clean_tweets']

story=[]
for tweet in tweets:
    raw_sent=sent_tokenize(tweet)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [43]:
import multiprocessing
cores = multiprocessing.cpu_count()

model12=gensim.models.Word2Vec( window=11,
                             min_count=2,
                             vector_size=300,
                             alpha=0.025,  
                             negative=20,
                             workers=cores-1,
                             sg=0
                             )
#sg=0 for skipgram and 1for cbow

In [36]:
model.build_vocab(story)

In [37]:
model.corpus_count

81404

In [38]:
model.train(story,total_examples=model.corpus_count,epochs=15,compute_loss=True)

(9797502, 11414955)

In [39]:
len(model.wv.index_to_key)

39378

In [40]:
model.wv.most_similar('date')

[('offbeat', 0.7222816348075867),
 ('types', 0.6945273876190186),
 ('bachelorau', 0.6611188650131226),
 ('sonofabitch', 0.6146183013916016),
 ('ladies', 0.5906879901885986),
 ('guessed', 0.5736902952194214),
 ('tgit', 0.5725183486938477),
 ('fucken', 0.5644412636756897),
 ('astound', 0.5620062351226807),
 ('fairs', 0.561787486076355)]

In [45]:
import pickle
pickle_out=open("vectorizer_model.pkl","wb")
pickle.dump(model12,pickle_out)
pickle_out.close()

In [46]:
model.wv.similarity('good','bad')

0.50383615

In [47]:
import numpy as np
from tqdm import tqdm

def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split(' ') if word in model.wv.index_to_key]
    
    if not doc:  # Check if the doc list is empty
        return np.zeros(model.vector_size)  # Return a zero vector or an appropriate default value
    
    return np.mean(model.wv[doc], axis=0)

X = []

for doc in tqdm(tweets):
    if isinstance(doc, float):
        doc = str(doc)
    
    X.append(document_vector(doc))

X = np.array(X)


100%|███████████████████████████████████████████████████████████████████████████| 81408/81408 [05:49<00:00, 232.62it/s]


In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.20,random_state=42)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# class_weights = {0: 5, 1: 3, 2: 3, 3: 3}

rf=RandomForestClassifier(n_estimators=300,random_state=42,n_jobs=-1)
rf.fit(X_train,y_train)
y_pred=rf.predict(X_test)

score=accuracy_score(y_test,y_pred)
print('Accuracy Score is: ', score)

print('Classifiaction report: ',classification_report(y_test,y_pred))
print('Confusion matrix: \n',confusion_matrix(y_test,y_pred))

Accuracy Score is:  0.5944601400319371
Classifiaction report:                precision    recall  f1-score   support

           0       0.03      0.02      0.02      4179
           1       0.58      0.66      0.62      4276
           2       0.97      0.99      0.98      3696
           3       0.60      0.75      0.67      4131

    accuracy                           0.59     16282
   macro avg       0.54      0.61      0.57     16282
weighted avg       0.53      0.59      0.56     16282

Confusion matrix: 
 [[  66 2049   35 2029]
 [1377 2836   50   13]
 [   4    3 3664   25]
 [ 965    7   46 3113]]


In [49]:
import numpy as np
from sklearn.linear_model import LogisticRegression

# Create a logistic regression model
model_ = LogisticRegression()

# Fit the model on the combined TF-IDF vectors
model_.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model_.predict(X_test)

# Convert Series objects to NumPy arrays and reshape
y_test = np.array(y_test).reshape(-1, 1)
y_pred = np.array(y_pred).reshape(-1, 1)

# Evaluate the model on the test data
accuracy = model_.score(X_test, y_test)
print("Accuracy:", accuracy)

print('Classification Report: \n ',classification_report(y_pred,y_test))
print('confusion matrix: \n ',confusion_matrix(y_pred,y_test))

Accuracy: 0.7354747574008107
Classification Report: 
                precision    recall  f1-score   support

           0       0.04      0.36      0.06       413
           1       0.97      0.67      0.79      6180
           2       1.00      1.00      1.00      3703
           3       0.96      0.66      0.79      5986

    accuracy                           0.74     16282
   macro avg       0.74      0.67      0.66     16282
weighted avg       0.95      0.74      0.82     16282

confusion matrix: 
  [[ 147  116    0  150]
 [2024 4154    1    1]
 [   1    6 3695    1]
 [2007    0    0 3979]]


C:\Users\Dell\anaconda3.1\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [50]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

# Create a BaLoggging Classifier
base_model =LogisticRegression()
bag_model = BaggingClassifier(base_estimator=base_model,n_jobs=-1,n_estimators=20,random_state=42,verbose=2)

# Fit the model on the training data
bag_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = bag_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   4 out of   4 | elapsed:  1.6min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   4 out of   4 | elapsed:    1.2s finished


Accuracy: 0.7354133398845351


In [ ]:
import pickle
pickle_out=open("model_.pkl","wb")
pickle.dump(bag_model,pickle_out)
pickle_out.close()